### ISSUE TITLE
Target private tags in Recipe (with exceptions)

### ISSUE THREAD

**Issue by samuelschuettler** [pydicom/deid#271]
I did not find the proper section in the documentation, but if i missed it please point me in the correct direction.

We are looking to have project specific recipes where we want to define the removal of private tags in the recipe itself (i know that it can be done with pydicom, but we want to store the instructions on wether or not to remove private tags in the recipe. Is that possible? I only find the python functions for that.)

Basically we are looking for the following:
```
%fields private_tags
SELECTOR_TO_SELECT_ALL_PRIVATE_TAGS
SELECTOR_TO_EXCLUDE_SPECIFIC_PRIVATE_RANGE_FROM_PREVIOUS SELECTION

%headers

REMOVE fields:private_tags
```

The usecase is that we want to remove all private tags per default but need to keep some in certain projects, when they are necessary for further processing, e.g. in vendor-provided tools.

How could we do that?  
A quick outline which features to plug together would be enough :-)

Thank you in advance

**Comment by wetzelj** [comment]
Hi @samuelschuettler,

There are probably multiple ways to do this. Since you want this all to be recipe-controlled, The first thought that comes to my mind is to use a custom function.  Since the selector that you'd need to have to determine if a tag is private is - "is the tag group odd", I can't think of a way that our current selectors could be used in this manner.

However, it would be possible for you to create a custom function that interrogated the tag group to determine if it was odd - returning true/false.  (See test method "[test_remove_all_func](https://github.com/pydicom/deid/blob/830966d52846c6b721fabb4cc1c75f39eabd55cc/deid/tests/test_replace_identifiers.py#L633)").  This test method shows how you could use a function to remove all fields that match a certain pattern.  Tweaking this pattern to look at the tag group should be trivial (if I'm recalling correctly - it's been a while :) ).

Once you get that part done, the inclusions would be simple, you could just use the KEEP action.  You wouldn't even need to use %fields sections.

With this approach your final recipe would be something like:
```
REMOVE ALL func:is_private_tag
KEEP 00090012
KEEP 00090013
KEEP 00090014
```

While the REMOVE action will tell deid to remove 00090012, the second KEEP action will override the remove, resulting in the field being retained.

**Comment by vsoch** [comment]
Thanks @wetzelj !

**Comment by samuelschuettler** [comment]
Thanks for the swift answer :-) 
That looks like a good solution.
