### ISSUE TITLE
items and lists

### ISSUE THREAD

**Issue by BrianKolowitz** [pydicom/deid#39]
I find it a bit confusing that I can past an item or a list into many methods and always get a list back in return. This pattern is reflected many times throughout the code

```python
# validate.py
if not isinstance(dcm_files,list):
        dcm_files = [dcm_files]
```

```python
# header.py
if not isinstance(dicom_files,list):
        dicom_files = [dicom_files]
```
etc. I think it would be cleaner if the methods only took lists as arguments.

**Comment by vsoch** [comment]
It's important that we are extremely consistent with regard to output, and very flexible for input. I think that it's very likely that a user will give a single file name, eg:

```
dicom_file = "so-amazing.dcm"
dothething(dicom_file)

and then for larger operations, a list.
dicom_files = ["so-amazing1.dcm", "so-amazing2.dcm"]
dothething(dicom_files)
```
And for both these use cases, the function should work equivalently and the user should get the same (consistent) output. Since we are dealing with functions that (typically) operate on multiple things (lists) I would choose the more consistent of the two (returning a list always). I could see an argument for returning the same format that was input (eg, if a single item is input, parse as list but then return back as single result) but I don't see the good rationale for having an extra error thrown if the input is slightly different. Could you explain why you think this is important?

**Comment by BrianKolowitz** [comment]
i think it's fine either way. I chased a bug for a while because I passed in a single file and got a list containing a single file in return which I didn't expect but do find acceptable.
